default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: nexttrace

test:
  <<: *default
  database: nexttrace_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "nexttrace") %>
  username: <%= ENV.fetch("DATABASE_USER", "nexttrace") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "nexttrace") %>
  host: <%= ENV["DATABASE_HOST"] %>
