steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '.',
          '-f', 'Dockerfile-base',
          '-t', 'gcr.io/${PROJECT_ID}/nexttrace-base' ]
options:
  machineType: 'N1_HIGHCPU_8'
images: ['gcr.io/${PROJECT_ID}/nexttrace-base']
