steps:
    - id: 'build  '
      name: 'gcr.io/cloud-builders/docker'
      args: [
        'build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}', '.',
        '--build-arg=COMMIT_SHA=${_COMMIT_SHA}',
        '--build-arg=COMMIT_TIME="${_COMMIT_TIME}"',
      ]

    - id: 'push   '
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

    - id: 'deploy '
      name: 'gcr.io/cloud-builders/gcloud'
      args: ["run", "deploy", "${_SERVICE}", 
            "--platform", "managed", 
            "--region", "${_REGION}",
            "--image", "gcr.io/$PROJECT_ID/${_SERVICE}"]

# substitutions:
#   _REGION: (the region)
#   _SERVICE: (the cloud run service)
#
# Automatically provided:
#   PROJECT_ID: (the project)
