steps:
    - id: 'build  '
      name: 'gcr.io/kaniko-project/executor'
      args: ['--destination=gcr.io/$PROJECT_ID/${_SERVICE}', '--cache=true']

    - id: 'push   '
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

    - id: 'deploy '
      name: 'gcr.io/cloud-builders/gcloud'
      args: ["run", "deploy", "${_SERVICE}", 
            "--platform", "managed", 
            "--region", "${_REGION}",
            "--image", "gcr.io/$PROJECT_ID/${_SERVICE}"]

# substitutions:
#   _REGION: (the region)
#   _SERVICE: (the cloud run service)
#
# Automatically provided:
#   PROJECT_ID: (the project)
